# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='qblog.Classification'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
